baseURL = "https://haesslicheplastiktiereundzeugs.projektemacher.org/"
languageCode = "de"
title = "Häßliche Plastiktiere und Zeugs"
publishDir = "docs"
canonifyurls = true
languagecode = "de"
defaultcontentlanguage = "de"
disablePathToLower = true

[menu]
    [[menu.main]]
        name = "Start"
        weight = 1
        url = "/"

    [[menu.main]]
        name = "Über"
        weight = 2
        url = "about/"

    [[menu.main]]
        name = "tags"
        weight = 3
        url = "tags/"
