baseURL = "https://haesslicheplastiktiereundzeugs.projektemacher.org/"
languageCode = "de"
title = "Hässliche Plastiktiere und Zeugs"
publishDir = "docs"
canonifyurls = true
languagecode = "de"
defaultcontentlanguage = "de"
disablePathToLower = true
rssLimit = 25
enableGitInfo = true
theme = "projektemacher-base"

[markup.goldmark]
    [markup.goldmark.renderer]
        unsafe= true

    [markup.goldmark.extensions]
        attribute = true
        strikethrough = true

    [markup.goldmark.extensions.typographer]
        apostrophe = '&rsquo;'
        disable = false
        ellipsis = '&hellip;'
        emDash = '&mdash;'
        enDash = '&ndash;'
        leftAngleQuote = '&laquo;'
        leftDoubleQuote = '&ldquo;'
        leftSingleQuote = '&lsquo;'
        rightAngleQuote = '&raquo;'
        rightDoubleQuote = '&rdquo;'
        rightSingleQuote = '&rsquo;'

    [markup.goldmark.extensions.extras]
        [markup.goldmark.extensions.extras.insert]
            enable = true
        [markup.goldmark.extensions.extras.mark]
            enable = true
        [markup.goldmark.extensions.extras.subscript]
            enable = true
        [markup.goldmark.extensions.extras.superscript]
            enable = true

    [markup.goldmark.parser]
        autoHeadingID = true
        autoHeadingIDType = "github"

[menu]
    [[menu.main]]
        name = "Start"
        weight = 1
        url = "/"

    [[menu.main]]
        name = "Über"
        weight = 2
        url = "about/"

[build]
  writeStats = true
