baseURL = "https://haesslicheplastiktiereundzeugs.projektemacher.org/"
languageCode = "de"
title = "Hässliche Plastiktiere und Zeugs"
publishDir = "docs"
canonifyurls = true
languagecode = "de"
defaultcontentlanguage = "de"
disablePathToLower = true
rssLimit = 25

[params]
    linkTumblr = true

[menu]
    [[menu.main]]
        name = "Start"
        weight = 1
        url = "/"

    [[menu.main]]
        name = "Über"
        weight = 2
        url = "about/"
