baseURL = "https://haesslicheplastiktiereundzeugs.projektemacher.org/"
languageCode = "de"
title = "Hässliche Plastiktiere und Zeugs"
publishDir = "docs"
canonifyurls = true
languagecode = "de"
defaultcontentlanguage = "de"
disablePathToLower = true
rssLimit = 25

[params]
    linkTumblr = true
    author = "Christian Mahnke"
    keywords = "Tierparaden, Stadtmöbel"
    description = "Fotodokumentaion über Tierparaden"

[markup.goldmark]
    [markup.goldmark.renderer]
        unsafe= true

    [markup.goldmark.extensions]
        attribute = true
        strikethrough = true

    [markup.goldmark.extensions.typographer]
        apostrophe = '&rsquo;'
        disable = false
        ellipsis = '&hellip;'
        emDash = '&mdash;'
        enDash = '&ndash;'
        leftAngleQuote = '&laquo;'
        leftDoubleQuote = '&ldquo;'
        leftSingleQuote = '&lsquo;'
        rightAngleQuote = '&raquo;'
        rightDoubleQuote = '&rdquo;'
        rightSingleQuote = '&rsquo;'

    [markup.goldmark.parser]
        autoHeadingID = true
        autoHeadingIDType = "github"

[menu]
    [[menu.main]]
        name = "Start"
        weight = 1
        url = "/"

    [[menu.main]]
        name = "Über"
        weight = 2
        url = "about/"
